name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: env
        run: |
          env
          echo -------
          echo ${{ github.ref }}
          echo -------
          echo ${{ github.ref_name }}

      - name: Build
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # settings/Actions/General (Read and write permissions)
          files: |
            dist/go-unpkg-downloader-darwin-arm64.tar.gz
            dist/go-unpkg-downloader-darwin-x64.tar.gz
            dist/go-unpkg-downloader-linux-x64.tar.gz
            dist/go-unpkg-downloader-win32-x64.zip
